# KPIs + Coding Preattentive Attributes

In [2]:
# import libraries
import pandas as pd
import numpy as np
import datetime

In [3]:
df = pd.read_csv('/home/ekmys/PycharmProjects/covid-19-vaccine-adverse-reactions/data/west_states_filtered.csv')

/tmp/ipykernel_57076/4243566829.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/home/ekmys/PycharmProjects/covid-19-vaccine-adverse-reactions/data/west_states_filtered.csv')

KPI checklist
- Total adverse events in [Month]
- % change in # adverse events (month)
- % reports where deaths were reported

## Total Adverse Events in (Month)

In [4]:
print(type(df['ONSET_DATE'][0]))

<class 'str'>

In [7]:
df['ONSET_DATE'] = df['ONSET_DATE'].astype('datetime64[ns]')
df['ONSET_YEAR'] = df['ONSET_DATE'].dt.year
df['MONTH_YEAR'] = df['ONSET_DATE'].dt.strftime('%Y-%m')
df.head()

,Unnamed: 0,VAERS_ID,symptom,RECVDATE,STATE,AGE_YRS,SEX,RPT_DATE,DIED,HOSPITAL,...,V_ADMINBY,V_FUNDBY,FORM_VERS,TODAYS_DATE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,ONSET_YEAR,ONSET_MONTHYEAR,MONTH_YEAR
0,1,902440,Headache,2020-12-15,AZ,35.0,F,NaN,N,N,...,PVT,UNK,2.0,2020-12-15,PFIZER\BIONTECH,EH9899,1.0,2020.0,2020-12,2020-12
1,9,902490,Headache,2020-12-15,NM,37.0,F,NaN,N,N,...,PVT,UNK,2.0,2020-12-15,PFIZER\BIONTECH,EH9899,1.0,2020.0,2020-12,2020-12
2,21,902557,Blood glucose normal,2020-12-15,AK,32.0,F,NaN,N,N,...,PVT,UNK,2.0,2020-12-15,PFIZER\BIONTECH,EK5730,1.0,2020.0,2020-12,2020-12
3,22,902557,Hyperhidrosis,2020-12-15,AK,32.0,F,NaN,N,N,...,PVT,UNK,2.0,2020-12-15,PFIZER\BIONTECH,EK5730,1.0,2020.0,2020-12,2020-12
4,29,902648,Feeling hot,2020-12-16,CA,26.0,F,NaN,N,N,...,PVT,UNK,2.0,2020-12-16,PFIZER\BIONTECH,EH9899,1.0,2020.0,2020-12,2020-12

In [8]:
# get groupby object
df_kpi_grouped = df.groupby(by=["MONTH_YEAR"]).agg(report_count=("VAERS_ID", 'count'))
df_kpi_grouped = df_kpi_grouped.reset_index()

In [9]:
df_kpi_grouped.head()

  MONTH_YEAR  report_count
0    2020-01           149
1    2020-02           106
2    2020-03            41
3    2020-04            37
4    2020-05            21

In [10]:
total_events_202011 = df_kpi_grouped[df_kpi_grouped['MONTH_YEAR'] == '2020-11']
total_events_202011 = total_events_202011.reset_index()

In [11]:
print(total_events_202011)

   index MONTH_YEAR  report_count
0     10    2020-11            19

In [12]:
report_count_202011 = total_events_202011.at[0,'report_count']
print(report_count_202011)

19

In [13]:
print(type(total_events_202011['report_count'][0]))

<class 'numpy.int64'>

In [14]:
# how do we get the sum of total events in the dataframe range?
# need sum of report counts
total_reports = df_kpi_grouped['report_count'].sum()
print(total_reports)

630935

In [15]:
def get_total_events_kpi(df: pd.DataFrame) -> str:
    df_kpi_grouped = (df.groupby(by=["MONTH_YEAR"]).agg(report_count=("VAERS_ID", "count"))).reset_index()
    total_reports = df_kpi_grouped['report_count'].sum()
    total_reports_str = str(total_reports)
    return total_reports_str

# could show rate of change from earliest date in the range to latest date in the range

In [16]:
get_total_events_kpi(df)

'630935'

# Total Number of Hospitalizations

In [17]:
# get filtered groupby object
df_hosp = df[df['HOSPITAL'] == 'Y']
df_hosp.head()
print(df_hosp['HOSPITAL'].unique().tolist())

['Y']

In [18]:
# get groupby object
df_kpi_hosp = (df_hosp.groupby(by=["MONTH_YEAR"]).agg(report_count=("VAERS_ID", "count"))).reset_index()

In [19]:
def get_total_hosp_kpi(df: pd.DataFrame) -> str:
    df_hosp = df[df['HOSPITAL'] == 'Y']
    df_kpi_hosp = (df_hosp.groupby(by=["MONTH_YEAR"]).agg(report_count=("VAERS_ID", "count"))).reset_index()
    total_hosp = df_kpi_hosp['report_count'].sum()
    total_hosp_str = str(total_hosp)
    return total_hosp_str

# could show rate of change from earliest date in the range to latest date in the range

In [20]:
get_total_hosp_kpi(df)

'43051'

# Total Number of Deaths

In [21]:
# get filtered groupby object
df_died = df[df['DIED'] == 'Y']
df_died.head()
print(df_died['DIED'].unique().tolist())

['Y']

In [22]:
# get groupby object
df_kpi_died = (df_died.groupby(by=["MONTH_YEAR"]).agg(report_count=("VAERS_ID", "count"))).reset_index()

In [23]:
def get_total_died_kpi(df: pd.DataFrame) -> str:
    df_died = df[df['DIED'] == 'Y']
    df_kpi_died = (df_died.groupby(by=["MONTH_YEAR"]).agg(report_count=("VAERS_ID", "count"))).reset_index()
    total_died = df_kpi_died['report_count'].sum()
    total_died_str = str(total_died)
    return total_died_str

# could show rate of change from earliest date in the range to latest date in the range

In [24]:
get_total_died_kpi(df)

'5447'

# Preattentive Attributes

In [34]:
# df_kpi_grouped.head()
df_kpi_grouped.tail()

   MONTH_YEAR  report_count
49    2024-02           390
50    2024-03           296
51    2024-04           208
52    2024-05           240
53    2024-06           116

In [35]:
print(len(df_kpi_grouped))

54

In [30]:
print(type(df_kpi_grouped['MONTH_YEAR'][0]))

<class 'str'>

## Percent change total

In [36]:
# get preattentives for total_adverse_events

# get total adverse events in first month of the range
first_month = df_kpi_grouped.at[0,'report_count']
print(first_month)

# get total adverse events in last month of the range
last_month = df_kpi_grouped.at[(len(df_kpi_grouped)-1), 'report_count']
print(last_month)

# calculate percent change
def percent_change (val1, val2):
    percent_change = ((val2 - val1) / abs(val1))*100
    return percent_change

149
116

In [38]:
pct_change = ((last_month - first_month) / abs(first_month))*100

In [39]:
print(pct_change)

-22.14765100671141

In [53]:
def get_percent_change_total(df: pd.DataFrame) -> float:
    df_kpi_grouped = (df.groupby(by=["MONTH_YEAR"]).agg(report_count=("VAERS_ID", "count"))).reset_index()
    first_month = df_kpi_grouped.at[0,'report_count']
    last_month = df_kpi_grouped.at[(len(df_kpi_grouped)-1), 'report_count']
    if first_month == 0:
        pct_change = '0 events reported in first month of date range.'
    else:
        pct_change = ((last_month - first_month) / abs(first_month))*100
        pct_change = round(pct_change, 2)
    return pct_change

In [54]:
get_percent_change_total(df)

np.float64(-22.15)

## Percent change hosp

In [55]:
def get_percent_change_hosp(df: pd.DataFrame) -> float:
    df_hosp = df[df['HOSPITAL'] == 'Y']
    df_kpi_hosp = (df_hosp.groupby(by=["MONTH_YEAR"]).agg(report_count=("VAERS_ID", "count"))).reset_index()
    first_month = df_kpi_hosp.at[0,'report_count']
    last_month = df_kpi_hosp.at[(len(df_kpi_hosp)-1), 'report_count']
    if first_month == 0:
        pct_change = '0 events reported in first month of date range.'
    else:
        pct_change = ((last_month - first_month) / abs(first_month))*100
        pct_change = round(pct_change, 2)
    return pct_change

In [56]:
get_percent_change_hosp(df)

np.float64(11.11)

## Percent change died

In [57]:
def get_percent_change_died(df: pd.DataFrame) -> float:
    df_died = df[df['DIED'] == 'Y']
    df_kpi_died = (df_died.groupby(by=["MONTH_YEAR"]).agg(report_count=("VAERS_ID", "count"))).reset_index()
    first_month = df_kpi_died.at[0,'report_count']
    last_month = df_kpi_died.at[(len(df_kpi_died)-1), 'report_count']
    if first_month == 0:
        pct_change = '0 events reported in first month of date range.'
    else:
        pct_change = ((last_month - first_month) / abs(first_month))*100
        pct_change = round(pct_change, 2)
    return pct_change

In [58]:
get_percent_change_died(df)

np.float64(-97.73)