In [ ]:
## Process from Dr. McGarry
# 1. check if data folder exists and if not create it
# 0. Check if file exists in data
# 1. download data from kagglehub
# 2. save it to our local disk
# 3. perform data transformations, preprocessing, cleaning, etc.
# 4. save clean version to local disk
# 5. /data folder is in .gitignore

In [1]:
# General packages from class
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import scipy.stats as stats

# Recommended packages from Kaggle
import kagglehub as kh
from kagglehub import KaggleDatasetAdapter

/home/ekmys/PycharmProjects/covid-19-vaccine-adverse-reactions/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
## Reading .csv from Kaggle.
# Download latest version
# Load the latest version
path = kh.dataset_download("ayushggarg/covid19-vaccine-adverse-reactions")

print("Path to dataset files:", path)

Path to dataset files: /home/ekmys/.cache/kagglehub/datasets/ayushggarg/covid19-vaccine-adverse-reactions/versions/7

In [11]:
# alternative method
# search: "Magic function" --> how to call CLI / bash function in Juptyer Notebook

import kaggle
#!/bin/bash
# % kaggle datasets download ayushggarg/covid19-vaccine-adverse-reactions

You must authenticate before you can call the Kaggle API.
Follow the instructions to authenticate at: https://github.com/Kaggle/kaggle-cli/blob/main/docs/README.md#authentication

NameError: name 'exit' is not defined

In [4]:
# create dataframe(s)

# concatenate strings
path_to_vax = path + '/VAERSVAX.csv'
path_to_symptoms = path + '/VAERSSYMPTOMS.csv'
path_to_VAERS = path + '/VAERSDATA.csv'

# df_vax_test = pd.read_csv()

In [5]:
# create dataframe for df_vax
df_vax_test = pd.read_csv(path_to_vax)
df_vax_test.head()

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME
0,902418,COVID19,PFIZER\BIONTECH,EH9899,1,IM,LA,COVID19 (COVID19 (PFIZER-BIONTECH))
1,902440,COVID19,PFIZER\BIONTECH,EH 9899,1,SYR,LA,COVID19 (COVID19 (PFIZER-BIONTECH))
2,902446,COVID19,PFIZER\BIONTECH,EH9899,1,IM,RA,COVID19 (COVID19 (PFIZER-BIONTECH))
3,902464,COVID19,PFIZER\BIONTECH,EH9899,UNK,IM,LA,COVID19 (COVID19 (PFIZER-BIONTECH))
4,902465,COVID19,PFIZER\BIONTECH,EH9899,1,IM,RA,COVID19 (COVID19 (PFIZER-BIONTECH))

In [6]:
# create dataframe for df_symptoms
df_symptoms_test = pd.read_csv(path_to_symptoms)
df_symptoms_test.head()

,VAERS_ID,SYMPTOM1,SYMPTOMVERSION1,SYMPTOM2,SYMPTOMVERSION2,SYMPTOM3,SYMPTOMVERSION3,SYMPTOM4,SYMPTOMVERSION4,SYMPTOM5,SYMPTOMVERSION5
0,902418,Hypoaesthesia,24.0,Injection site hypoaesthesia,24.0,NaN,NaN,NaN,NaN,NaN,NaN
1,902440,Headache,23.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,902446,Erythema,23.1,Feeling hot,23.1,Flushing,23.1,NaN,NaN,NaN,NaN
3,902464,Dizziness,23.1,Electrocardiogram normal,23.1,Hyperhidrosis,23.1,Laboratory test normal,23.1,Presyncope,23.1
4,902465,Dysgeusia,23.1,Oral pruritus,23.1,Paraesthesia,23.1,Paraesthesia oral,23.1,Parosmia,23.1

Note 2/25/2026 - We can download from kaggle the CSV files for symptoms and vax, but for whatever reason the VAERSDATA.csv file is missing. Not sure what's going on there.